### ISSUE TITLE
Отсутствует зеленый треугольник у main

### ISSUE THREAD

**Issue by e-n-o-t-e** [Kotlin-Polytech/KotlinAsFirst-Coursera-v2021#2]
Отсутствует зеленый треугольник у функции main.
Maven выдает следующее:
Sync
   Resolve dependencies
          Cannot resolve ru.spbstu:kfirst-bom:22.0.0

В версии от 2022г. тоже самое.
В то же время, при тех же настройках Project Structure,  версия 2019 работает. 
Возможно что то делаю не так

**Comment by AbdullinAM** [comment]
Спасибо за информацию. Проблему исправили, теперь все должно работать

На будущее: данный репозиторий будет перемещен в архив, т.к. курс на Coursera больше недоступен. На парах вы будете использовать репозиторий [KotlinAsFirst-2022](https://github.com/Kotlin-Polytech/KotlinAsFirst-2022). Более подробно о том как все нужно сделать вам расскажут на первых парах
